name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: sardarali
          repo: nodepro1
          github_token: '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'
          workflow_file_name: /.github/workflows/node.yml
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s
