name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: sardaralii
          repo: nodepro1
          github_token: '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'
          workflow_file_name: node1.yml
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s
