name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: echo "Build Web App" && sleep 10s

      - name: Trigger Workflow in Another Repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: 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
          repository: sardarali/nodepro1
          event-type: my-custom-event
          
